name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm' # for not downloading dependencies again and again 

      # --- STEP 1: FRONTEND BUILD AUTOMATION ---
      - name: Install Frontend Dependencies & Build
        run: |
          cd frontend                
          npm ci                     
          npm run build              
          cp -r build/* ../backend/public/   

      # --- STEP 2: BACKEND SETUP ---
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      # --- STEP 3: CYPRESS AUTOMATED TESTS ---
      - name: Run Tests
        run: echo "No tests configured"

  cd:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"